[pytest]
pythonpath = .
testpaths = tests
addopts = -ra -p no:cacheprovider
markers =
    web: web ui tests
    api: api tests
    mobile: mobile app tests
    contract: ui and api consistency checks
