name: postman-ci

on:
  workflow_dispatch:

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Newman
        run: npm install -g newman
      - name: Run Postman smoke
        run: >
          newman run bagisto_qa_portfolio/postman/Bagisto_Smoke.postman_collection.json
          -e bagisto_qa_portfolio/postman/dev.postman_environment.json
